schema:
- name: delivery_day
  type: string
- name: ingestion_time
  type: timestamp
- name: hour_1
  type: double
- name: hour_2
  type: double
- name: hour_3
  type: double
- name: hour_4
  type: double
- name: hour_5
  type: double
- name: hour_6
  type: double
- name: hour_7
  type: double
- name: hour_8
  type: double
- name: hour_9
  type: double
- name: hour_10
  type: double
- name: hour_11
  type: double
- name: hour_12
  type: double
- name: hour_13
  type: double
- name: hour_14
  type: double
- name: hour_15
  type: double
- name: hour_16
  type: double
- name: hour_17
  type: double
- name: hour_18
  type: double
- name: hour_19
  type: double
- name: hour_20
  type: double
- name: hour_21
  type: double
- name: hour_22
  type: double
- name: hour_23
  type: double
- name: hour_24
  type: double
