#####  THIS IS JUST A SAMPLE FILE ACTUAL CI/CD depolyment file will be different############## 

name: CI/CD - AWS Glue Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Set up Node.js (for CDK)
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install CDK and dependencies
      run: |
        npm install -g aws-cdk
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: CDK Bootstrap
      run: |
        source .venv/bin/activate
        cdk bootstrap

    - name: CDK Deploy (auto-approve)
      run: |
        source .venv/bin/activate
        cdk deploy --all --require-approval never

    - name: Upload Glue Scripts to S3
      run: |
        aws s3 cp energy_pipeline_cdk/glue_jobs/ s3://<your-bucket-name>/scripts/ --recursive
